branch-defaults:
  default:
    environment: ebnode-dev
    group_suffix: null
global:
  application_name: ebnode
  default_ec2_keyname: UbuntuJosephN
  default_platform: Node.js
  default_region: us-east-1
  profile: null
  sc: null
